on: [pull_request]

jobs:
  server-run-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/api  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12.2
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --frozen --no-dev

      - name: Run API test
        run: |
          uv run pytest